#!/bin/bash

echo "PostgreSQL Setup Script for LMS"
echo "================================"
echo ""
echo "Please run these commands to set up PostgreSQL:"
echo ""
echo "1. Install PostgreSQL (if not already installed):"
echo "   sudo apt update"
echo "   sudo apt install postgresql postgresql-client"
echo ""
echo "2. Start PostgreSQL service:"
echo "   sudo systemctl start postgresql"
echo "   sudo systemctl enable postgresql"
echo ""
echo "3. Set up the database and user:"
echo "   sudo -u postgres psql << EOF"
echo "   CREATE USER lmsuser WITH PASSWORD 'lmspassword123';"
echo "   CREATE DATABASE lms_database OWNER lmsuser;"
echo "   GRANT ALL PRIVILEGES ON DATABASE lms_database TO lmsuser;"
echo "   \q"
echo "   EOF"
echo ""
echo "4. Update the .env file DATABASE_URL to:"
echo "   DATABASE_URL=\"postgresql://lmsuser:lmspassword123@localhost:5432/lms_database?schema=public\""
echo ""
echo "5. Run Prisma migrations:"
echo "   npx prisma db push"
echo "   npx prisma generate"
echo ""
echo "Alternative: If you already have PostgreSQL with different credentials,"
echo "just update the .env file with your existing database details."